### ISSUE TITLE
New Potion & Server Side only Support

### ISSUE THREAD

**Issue by C0D6WasTaken** [BoyPika/bring-back-luck#2]
# New Potion
I am currently looking for a mod that adds 3 potions: decay, luck and glow. I was hoping that you could combine your two mods and add another potion to the mix. 
If this seems appealing, you could make a simple configuration file to toggle features on and off.

# Limiting the mod to the server side only
This would allow players with a vanilla client installed to play.
Textures are unnecessary, so I believe they should be optional for servers. You could make them appear only to client-side users of the mod.
You could also add vanilla brewing recipes for all potions. Here's a brewing guide I just thought of: 
![brewingGuideLarge](https://github.com/BoyPika/bring-back-luck/assets/87787951/a6160ac8-30a2-43fb-a055-bfdfaac126cf)
(The dark theme seemed like a good idea until I realised that wither roses are black)

**Comment by BoyPika** [comment]
https://github.com/BoyPika/Mo-Potions/releases/tag/Release
