### ISSUE TITLE
add fstats

### ISSUE THREAD

**Issue by BoyPika** [BoyPika/bring-back-luck#7]

**Comment by BoyPika** [comment]
I think I have it working

**Comment by syorito-hatsuki** [comment]
Hi. That line is not needed for fStats. Currently, it works only when running as a dedicated server and it already has been notified about that. Client-side support is planned for next year.
https://github.com/BoyPika/bring-back-luck/blob/93a9a4312c54953642638e1ec56f691646492ad9/src/main/java/net/boypika/bring_back_luck/Bring_Back_Luck.java#L27-L29
